version: "3"
services:
  selenium-standalone-firefox:
    image: selenium/standalone-firefox:4.0.0-beta-1-prerelease-20210106
    container_name: selenium-firefox
    shm_size: 2gb
    ports:
      - "4444:4444"